- name: 2.14 Ensure the 'sa' Login Account has been renamed
  win_shell: "invoke-sqlcmd -ServerInstance {{ ansible_hostname }} -Query \"SELECT name
FROM sys.server_principals
WHERE sid = 0x01;\"| ConvertTo-Json"
  register: result_214

- set_fact:
    ids: "{{ result_214.stdout|from_json}}"
- debug:
        var: ansible_hostname
- debug:
        var: ids
- debug:
        var: ids.name
# - debug:
#         var: ids.value_configured
# - debug:
#         var: ids.value_in_use
# - name: Check Condition
#   set_fact:
#     resultCheck213: "{{ ids.is_disabled == true }}"
# - debug:
#     var: resultCheck213
- debug:
        var: ansible_ip_addresses[0]

- name: Modules Write log file
  import_tasks: ../../../../modules/logs.yml
  vars:
    timestamp: "{{ ansible_date_time.iso8601 }}"
    destination_ip: "{{ ansible_ip_addresses[0] }}"
    playbook_type: "{{ PLAYBOOK_NAME }}"
    section_control_hardening: "Secure Boot Settings"
    task_number_control_hardening: "2.14"
    task_control_hardening: "Ensure the 'sa' Login Account has been renamed"

    result_flag: "{{ resultCheck213 }}"
    remark: ""