- name: 3.4 Ensure SQL Authentication is not used in contained databases
  win_shell: "invoke-sqlcmd -ServerInstance {{ ansible_hostname }} -Query \"SELECT name AS DBUser
FROM sys.database_principals
WHERE name NOT IN ('dbo','Information_Schema','sys','guest')
AND type IN ('U','S','G')
AND authentication_type = 2;\" "
  register: result_34

- set_fact:
    ids: "{{ result_34}}"
- debug:
        var: ansible_hostname
- debug:
        var: ids
- debug:
        var: ids.stdout

- name: Check Condition
  set_fact:
    resultCheck34: "{{ ids.stdout is none}}"
- debug:
    var: resultCheck34
- debug:
        var: ansible_ip_addresses[0]

- name: Modules Write log file
  import_tasks: ../../../../modules/logs.yml
  vars:
    timestamp: "{{ ansible_date_time.iso8601 }}"
    destination_ip: "{{ ansible_ip_addresses[0] }}"
    playbook_type: "{{ PLAYBOOK_NAME }}"
    section_control_hardening: "Secure Boot Settings"
    task_number_control_hardening: "3.4"
    task_control_hardening: "Ensure SQL Authentication is not used in contained databases"
    result_flag: "{{ resultCheck34 }}"
    remark: ""