- name: 2.16 Ensure 'AUTO_CLOSE' is set to 'OFF' on contained databases
  win_shell: "invoke-sqlcmd -ServerInstance {{ ansible_hostname }} -Query \"SELECT name, containment, containment_desc, is_auto_close_on
    FROM sys.databases
    WHERE containment <> 0 and is_auto_close_on = 1;\" "
  register: result216

- set_fact:
    ids: "{{ result216}}"
- debug:
        var: ansible_hostname
- debug:
        var: ids
- debug:
        var: ids.stdout

- name: Check Condition
  set_fact:
    resultCheck216: "{{ ids.stdout is none }}"
- debug:
    var: resultCheck216
- debug:
        var: ansible_ip_addresses[0]

- name: Modules Write log file
  import_tasks: ../../../../modules/logs.yml
  vars:
    timestamp: "{{ ansible_date_time.iso8601 }}"
    destination_ip: "{{ ansible_ip_addresses[0] }}"
    playbook_type: "{{ PLAYBOOK_NAME }}"
    section_control_hardening: "Secure Boot Settings"
    task_number_control_hardening: "2.16"
    task_control_hardening: "Ensure Ensure 'AUTO_CLOSE' is set to 'OFF' on contained databases"
    result_flag: "{{ resultCheck216 }}" 
    remark: ""