- name: 2.17 Ensure no login exists with the name 'sa'
  win_shell: "invoke-sqlcmd -ServerInstance {{ ansible_hostname }} -Query \"SELECT principal_id, name
FROM sys.server_principals
WHERE name = 'sa';\" "
  register: result_217

- set_fact:
    ids: "{{ result_217}}"
- debug:
        var: ansible_hostname
- debug:
        var: ids
- debug:
        var: ids.stdout

- name: Check Condition
  set_fact:
    resultCheck217: "{{ ids.stdout is none}}"
- debug:
    var: resultCheck217
- debug:
        var: ansible_ip_addresses[0]

- name: Modules Write log file
  import_tasks: ../../../../modules/logs.yml
  vars:
    timestamp: "{{ ansible_date_time.iso8601 }}"
    destination_ip: "{{ ansible_ip_addresses[0] }}"
    playbook_type: "{{ PLAYBOOK_NAME }}"
    section_control_hardening: "Secure Boot Settings"
    task_number_control_hardening: "2.17"
    task_control_hardening: "Ensure no login exists with the name 'sa'"
    result_flag: "{{ resultCheck217 }}"
    remark: ""